<style>
<!--
img{
	border: 1px solid #AAA;
	border-radius: 4px;
}
body{
	background-color: #ccf;
	margin-left: auto;
	margin-right: auto;
	width: 1050px;
}
-->
</style>
<div>
<!-- <a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/jiepang'?>"><img src="<?php echo $this->baseUrl() . '/images/jiepang_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/qq'?>"><img src="<?php echo $this->baseUrl() . '/images/qq_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/sina'?>"><img src="<?php echo $this->baseUrl() . '/images/sina_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/baidu'?>"><img src="<?php echo $this->baseUrl() . '/images/baidu_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/google'?>"><img src="<?php echo $this->baseUrl() . '/images/google_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/kaixin'?>"><img src="<?php echo $this->baseUrl() . '/images/kaixin_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/taobao'?>"><img src="<?php echo $this->baseUrl() . '/images/taobao_t.png'?>"/></a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/renren'?>"><img src="<?php echo $this->baseUrl() . '/images/renren_t.png'?>"/></a>
<a><img src="<?php echo $this->baseUrl() . '/images/none.png'?>"/></a>
<a href="<?php echo $this->baseUrl() . '/ApiTools/crawl'?>">后台</a>-->

<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/jiepang'?>">街旁</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/qq'?>">腾讯</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/sina'?>">新浪</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/baidu'?>">百度</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/google'?>">谷歌</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/kaixin'?>">开心</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/taobao'?>">淘宝</a>
<a href="<?php echo  $this->baseUrl() . '/ApiTools/Api/renren'?>">人人</a>
<a>期待中</a>
<a href="<?php echo $this->baseUrl() . '/ApiTools/crawl'?>">后台</a>
</div>