
<!--  <form method="post">
	<label>url</label><inp$array_expressionut type="text" name="url"/>
	<label>params</label><input type="text" name="params"/>
	<label>http</label><input type="text" name="http">
	<input type="submit">
</form>
<a href="<?php echo $this->url?>">验证</a>!-->

<script type="text/javascript">
<!--
	$(document).ready(function(){
		$('#catalog_select').change(function(){
			var url = '/GoodMgr/index.php/ApiTools/Api/sina';
			$.getJSON(url,{'catalog': $(this).val()},function(data){
				var options = '';
				$('#api_desc').html(data[0].api_desc);
				$.each(data, function(index, api){
					options += '<option value="' + api.id + '">' + api.name + '</option>';
					});
				$('#api_select').html(options);
				});
			});//end catalog select

		$('#api_select').change(function(){
			var url = '/GoodMgr/index.php/ApiTools/Api/sina';
			$.getJSON(url, {'api': $(this).val()}, function(data){
				$('#api_desc').html(data.api_desc);
				var param_html = '';
				$.each(data.param_names, function(index, name){
					param_html+='<div class="param_item">' +
						'<div class="param_name">' + name +'</div>' +
						'<div class="param_value"><input type="text" name="' + name +'"/></div>' +
						'<div class="param_desc">'+ data.param_desc[index] +'</div>' +
					'</div>';
					});
    				$('.param_item').remove();
    				$(param_html).appendTo($('#param_content'));
				});
		}); // end api select

		$('.param_item_head a').toggle(
						function(){ $(this).text('▼'); $('#param_content').toggle(); },
						function(){ $(this).text('▲'); $('#param_content').toggle(); });

		$('#send_btn').click(function(){
				var url = '/GoodMgr/index.php/ApiTools/Api/sina';
				$.post(url, $('#apiform').serialize(), function(data){
						if(data.url){
							window.location= data.url;
							}
						else{
							alert(data);
							$('#api_response').text(JSON.stringify(data.response, null, '\t'));
							//$('#api_response').text(pretty_json(JSON.stringify(data.response)));
							$('#api_request').text(JSON.stringify(data.request));
							}
					});
			});
	});//end document ready



	function pretty_json(text) {
		shift = ['\n'];
		step = '    '; // 4 spaces
		var maxdeep = 100, // nesting level
			ix = 0;

		// initialize array with shifts //
		for(ix=0;ix<maxdeep;ix++){
			shift.push(shift[ix]+step); 
		}
			
		var ar = text.replace(/\{/g,"~::~{~::~")
									.replace(/\[/g,"[~::~")
									.replace(/\}/g,"~::~}")
									.replace(/\]/g,"~::~]")
									.replace(/\"\,/g,'",~::~')
									.replace(/\,\"/g,',~::~"')
									.replace(/\]\,/g,'],~::~')
									.replace(/~::~\s{0,}~::~/g,"~::~")
									.split('~::~'),
					
			len = ar.length,
			deep = 0,
			str = '',
			ix = 0;

		for(ix=0;ix<len;ix++) {
			if( /\{/.exec(ar[ix]))  { 
				str += shift[deep++]+ar[ix];
			} else 
			if( /\[/.exec(ar[ix]))  { 
				str += shift[deep++]+ar[ix];
			}  else 
			if( /\]/.exec(ar[ix]))  { 
				str += shift[--deep]+ar[ix];
			}  else 
			if( /\}/.exec(ar[ix]))  { 
				str += shift[--deep]+ar[ix];
			} else {
				str += shift[deep]+ar[ix];
			}
		}
		return str.replace(/^\n{1,}/,'');
	}
//-->
</script>
<div>
	<form method="post" id="apiform">
		<div id="provider_catalog">
			<label for="catalog_select">目录</label>
			<select id="catalog_select">
				<?php 
					foreach ( $this->apiList->catalogs as $catalog) {?>
					<option value="<?php echo $this->escape($catalog['id'])?>"><?php echo $this->escape($catalog['name'])?></option>
				<?php }?>
			</select>
		</div>
		<div id="provider_api">
			<label for="api_select">API</label>
			<select id="api_select">
				<?php foreach ($this->apiList->apis as $api){?>
					<option value="<?php echo $this->escape($api['id'])?>"><?php echo $this->escape($api['name'])?></option>
				<?php }?>
			</select>
			<div id="http_type">
    			<?php 
    			switch ($this->apiList->apis[0]['method']) {
    			    case 0:
        			    echo "GET";
        			    break;
    			    case 1:
    			        echo "POST";
    			        break;
    			}?>
			</div>
			<div id="api_desc">
			    <?php echo $this->escape($this->apiList->apis[0]['api_desc'])?>
			</div>
			
			<div id="api_param">
				<div class="param_item_head">
					<div class="param_name_head">参数名</div>
					<div class="param_value_head">参数值</div>
					<div class="param_desc_head">注释</div>
					<a href="#">▲</a>
				</div>
				<div id="param_content">
				<?php $i = 0; foreach ($this->apiList->apiDetails['param_names'] as $param) {?>
				<div class="param_item">
					<div class="param_name"><?php echo $this->escape($param)?></div>
					<div class="param_value"><input type="text" name="<?php echo $this->escape($param)?>"/></div>
					<div class="param_desc"><?php echo $this->escape($this->apiList->apiDetails['param_desc'][$i])?></div>
				</div>
				<?php $i++; }?>
				</div>
			</div>			
		</div>
		<div id="api_send">
			<a id="send_btn" href="#">获得结果</a>
		</div>
		<div id="result">
			<div class="api_result">
				<div class="result_title">API请求</div>
				<div id="api_request"></div>
			</div>
			<div class="api_result">
				<div class="result_title">API结果</div>
				<!-- <textarea id="api_response"></textarea>-->
				<div id="api_response"></div>
			</div>
		</div>
		
		
	</form>
</div>
